CREATE TABLE USERS(
  id INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100)
);

ALTER TABLE USERS
ADD PASSWORD VARCHAR(100),
ADD ROLE VARCHAR(50),
ADD INSS VARCHAR(20),
ADD LASTNAME VARCHAR(40),
ADD FIRSTNAME VARCHAR(40),
ADD STREET VARCHAR(60),
ADD HOUSENUMBER VARCHAR(10),
ADD POSTALCODE VARCHAR(10),
ADD CITY VARCHAR(20);